### ISSUE TITLE
links in design doc reference an old version of OSM

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm-docs#10]
**Please describe what should be documented
Links should point to docs in main so they are up to date. When a release is cut, the links should be updated to point to a version of the documentation.

See example links in [this section ](https://github.com/openservicemesh/osm/blob/main/DESIGN.md#containers)of the design doc

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/openservicemesh/osm-docs/issues/22.
