### ISSUE TITLE
disambiguate version display text

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-docs#105]
It seems that investigation is warranted to find out what a "version" looks like (if it ever shows in the expected windows).

"The header at the top of the webpage indicates the application and version" from https://github.com/openservicemesh/osm-docs/blame/main/content/docs/install/manual_demo.md#L397 is confusing.

There is a header showing application names, like "Bookbuyer" in these screenshots, but it does not display "version" in the sense of OSM release version or anything else in the case of the Bookbuyer app.

Version: v0.8.4; Commit: 3d923b3f2d72006f6cdaad056938c492c364196d; Date: 2021-05-18-19:14

![image](https://user-images.githubusercontent.com/2104453/119912409-0eea6380-bf21-11eb-966a-9b55a8cee503.png)

 
compare versus:
 
Version: dev; Commit: 5b0a5d99e692fa0e43d2c39e4ad7cc32abc1f689; Date: 

![image](https://user-images.githubusercontent.com/2104453/119912396-05f99200-bf21-11eb-8967-566c423057db.png)

According to @shashankram this might be referring to "the application version (bookstore v1 or v2) or the image tags for the containers based on the release version". I propose we find when and if the version shows up, and insert an image next to the possibly-updated text, perhaps explaining which apps (like bookstore?) show a version.

**Comment by bridgetkromhout** [comment]
Update - this text is now part of https://release-v1-2.docs.openservicemesh.io/docs/getting_started/install_apps/ - does a header somewhere indicate a version now?

**Comment by zr-msft** [comment]
I propose the UI of the demo app use the container names (ie `bookstore-v1` and `bookstore-v2`) to avoid confusion.

Here's a PR with proposed changes:
https://github.com/openservicemesh/osm/pull/5129

@bridgetkromhout and @shashankram can you take a look and let me know what you think?

**Comment by bridgetkromhout** [comment]
Closing as we will no longer be making this change.
