### ISSUE TITLE
Error in OSM MeshConfig

### ISSUE THREAD

**Issue by allenlsy** [openservicemesh/osm-docs#117]
On the OSM MeshConfig page, I suspect the initSidecarContainer value is incorrect. I don't see OSM has envoy-alpine images on Docker Hub.

https://github.com/openservicemesh/osm-docs/commit/53833bdd7a27118aee9671baca4644047744a674#diff-b022770f740309db99120ed67855facd985c5e26064d057392e0ee2afda86bd2R56

Can we clarify or fix it?

**Comment by snehachhabria** [comment]
@allenlsy there is a mistake there please could we update it to the following :  |spec.sidecar.initContainerImage | string | `"openservicemesh/init:v0.8.4"` | `kubectl patch meshconfig osm-mesh-config -n osm-system -p '{"spec":{"sidecar":{"initContainerImage":"openservicemesh/init:v0.8.4"}}}'  --type=merge` |

**Comment by bridgetkromhout** [comment]
Fixed in https://github.com/openservicemesh/osm-docs/pull/118
