### ISSUE TITLE
using params.oldversion

### ISSUE THREAD

**Issue by zr-msft** [openservicemesh/osm-docs#128]
@flynnduism i have the following PRs for the 0.9 release:

#125 #126 #127

only the release-v0.8 branch (and #127) use params.oldversion 

How should this be updated in #127?
Do we also need to include in release-v0.9 and #126?

cc @bridgetkromhout

**Comment by flynnduism** [comment]
Looking at this, each of those PRs uses `[[params.versions]]`, I don't see `[[params.oldversions]]` anywhere. I'm unsure what you mean with this question.

Those 3 pull requests look good to go, adding 0.9 to the list of releases 👍🏻 

--

I have created the subdomain so release-v0-9.docs.openservicemesh.io is now in place.

**Comment by zr-msft** [comment]
@flynnduism oldversions is part of #127:

https://github.com/openservicemesh/osm-docs/pull/127/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77L96

**Comment by bridgetkromhout** [comment]
Thanks for setting up the subdomain, @flynnduism. Can you give us insight into what this means?
```
[[params.versions]]
  version = "latest"
  url = "https://docs.openservicemesh.io/"
[[params.versions]]
  version = "v0.9"
  url = "https://release-v0-9.docs.openservicemesh.io/"
[[params.versions]]
  version = "v0.8"
  url = "https://release-v0-8.docs.openservicemesh.io/"
[params.oldversion]
        show = true
        archive = "v0.8"
        latest = "https://docs.openservicemesh.io/"
```

**Comment by flynnduism** [comment]
Ah I see - after digging around I see this was something that I added for archival versions of the site (in [84fc48](https://github.com/zr-msft/osm-docs/commit/8edf0dd0177eb5b5275c99ab704c79beef84fc48 )), but should have explained and doc'd properly. 

The `params.oldversion` is an additional value that should reflect the current version you are looking at. It is rendered in the sticky banner at the top of the site

**I must apologize for not documenting this in the site versioning notes. I will do so now!**

---

It populates this banner:

![Screen Shot 2021-06-15 at 10 11 37 AM](https://user-images.githubusercontent.com/686194/122095335-18e5e080-cdc2-11eb-8a25-683f9fecb2b8.png)

In creating this, I think it's poorly named - having version and oldversion beside each other makes it seem like they're tied together. Really `oldversion` should be `versionbanner` or something.
 
What these parameters do:

```
[params.oldversion]
    show = true        <- enable or diable the navy banner at the top of the site
    archive = "v0.8"   <- tells the user what version they are currently looking at
    latest = "https://docs.openservicemesh.io/"    
                       ^-- the url for the main branch (latest) docs, should not change
```

@zr-msft to answer your question, on the `0.8` site, it does not need to be updated. This value states that you are viewing the 0.8 site, which will not change.

Whether or not this should be included in the `release-v0.9` site I think is up to you, it basically adds the banner to denote that you are not looking at the latest docs - but `0.9` is just a day or so old so there's not really a difference between `0.9` and `main`. The clarity can't hurt though, I would be inclined to add it.

**Comment by bridgetkromhout** [comment]
@flynnduism thanks for the detailed explanation! What needs to happen next? I think we do need the v0.9 site to say that it's an archive, since time will continue to move in the usual direction. Do we want to refactor that `oldversion` setting to be called `versionbanner`?

**Comment by flynnduism** [comment]
@bridgetkromhout yes to both I think. I will refactor the `oldversion` to a better name now

**Comment by bridgetkromhout** [comment]
Thanks, @flynnduism! I think the only thing left now is to make sure this is clear in the README. I'm thinking maybe we link to something like https://github.com/openservicemesh/osm-docs/blob/release-v0.9/config.toml#L84-L96 so people can see the whole situation, and then we get specific about what to edit? "Add these params" in https://github.com/openservicemesh/osm-docs/blame/main/README.md#L40 is a little unclear.

**Comment by flynnduism** [comment]
> "Add these params" in https://github.com/openservicemesh/osm-docs/blame/main/README.md#L40 is a little unclear.

Thanks for the feedback, I'll take another pass at the README copy

**Comment by bridgetkromhout** [comment]
Thanks. This is fully resolved by https://github.com/openservicemesh/osm-docs/pull/131.
