### ISSUE TITLE
Suggestion for a dark theme UI

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm-docs#199]
Can we have a Dark UI theme also for the docs website?

**Comment by bridgetkromhout** [comment]
Hi, @mudit-01 - thanks for the suggestion; while we can definitely consider a pull request, we cannot commit to having the project maintainers carry out dark UI theme work for the project website. Thanks.

**Comment by bridgetkromhout** [comment]
Hi, Mudit! Appreciate the idea; please do re-open if/when you want to work on it, as the project isn't currently able to do this specific UI work on the website design.
