### ISSUE TITLE
Fix duplicate headings on pages

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm-docs#20]
Some pages such as https://docs.openservicemesh.io/docs/ha/ have the title displayed twice. Address this.

![image](https://user-images.githubusercontent.com/21697719/117888089-7c7e6a80-b266-11eb-9b8c-3fca1023b081.png)

**Comment by bridgetkromhout** [comment]
Some of these issues were fixed in https://github.com/openservicemesh/osm-docs/pull/25 - we need to verify if more remain.

**Comment by bridgetkromhout** [comment]
related: https://github.com/openservicemesh/osm-docs/issues/7

**Comment by Atharva321** [comment]
Found this one also
https://docs.openservicemesh.io/docs/tasks_usage/observability/

**Comment by bridgetkromhout** [comment]
Fixes in https://github.com/openservicemesh/osm-docs/pull/41
