### ISSUE TITLE
Fix code links to point to main and/or be inlined

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm-docs#22]
**Please describe what should be documented**
All the links on this page currently point to v0.3 of OSM documentation. https://github.com/openservicemesh/osm/blob/main/docs/content/docs/design_concepts/osm_components_interactions/_index.md

These should be updated to point to most recent docs. Some pages/lines linked to here no longer exist. Links should also work on the docs site:
https://docs.openservicemesh.io/docs/design_concepts/osm_components_interactions/

Need to consider relative linking and aliasing for this change as mentioned [here](https://github.com/bridgetkromhout/osm/blob/relative-links/docs/README.md) (and explained by issue https://github.com/openservicemesh/osm/issues/2453)

**Comment by bridgetkromhout** [comment]
Deep-linking to unversioned code blocks will lead to the examples becoming inaccurate over time. We should instead excerpt the relevant examples into the website and then link to the code with a version indicated, for reference.

**Comment by bridgetkromhout** [comment]
The task here is to excerpt/inline code where it makes sense, to prevent stale links.

**Comment by zr-msft** [comment]
closing as this issue is no longer relevant
