### ISSUE TITLE
Document leveraging existing PKI infrastructure with OSM

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-docs#223]
Document how to use existing CAs w/ OSM (Hashicorp Vault and cert-manager.io integration).
Document the capabilities OSM's Hashicorp Vault and Cert-manager.io bring to the mesh.

**Comment by keithmattix** [comment]
Bumping this back up; cert-manager has the ability to work with customers' existing PKI infrastructure via the CA issuer; we should have an example or demo of this on the docs site
