### ISSUE TITLE
Blog page has too much white spaces 

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm-docs#288]
https://openservicemesh.io/blog/ Has too much white space even after 80% view
![blog page](https://user-images.githubusercontent.com/53465654/144386504-4d7801b3-e4dd-4933-b9d2-1aa74282c02c.jpg)

**Comment by bridgetkromhout** [comment]
Hi, Mudit! Appreciate your perspective on website design. As we aren't currently planning any design overhaul, I'll close this request out; however, if you do want to prototype a design update, we're happy to take a look. Thanks.
