### ISSUE TITLE
Update command parameters to reflect new values.yaml structure for v1.0

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm-docs#302]
As OSM v1.0 variables in the values.yaml are now defined under "osm" and not "OpenServiceMesh," our commands to update these values in our docs should be updated to reflect this. 

For instance, in the Manual Demo docs, we need to change `osm install --set=OpenServiceMesh.enablePermissiveTrafficPolicy=true` to `osm install --set=osm.enablePermissiveTrafficPolicy=true`

**Comment by shashankram** [comment]
Needs to be fixed in main and release-v1.0
