### ISSUE TITLE
mirror the v0.8 release docs

### ISSUE THREAD

**Issue by bridgetkromhout** [openservicemesh/osm-docs#36]
Add a v0.8 mirror of the docs as they existed in https://github.com/openservicemesh/osm/tree/release-v0.8/docs (available in a drop-down and not updated).

**Comment by flynnduism** [comment]
I've downloaded that release branch and pushed the docs here  as a `release-v0.8` [branch](https://github.com/openservicemesh/osm-docs/tree/release-v0.8). 

The push triggers Netlify to deploy that branch as https://release-v0-8--osm-docs.netlify.app/
Do we want to expose this link on the site in the dropdown?

**Comment by bridgetkromhout** [comment]
> I've downloaded that release branch and pushed the docs here as a release-v0.8 branch.

Awesome; thanks!

> Do we want to expose this link on the site in the dropdown?

Yes. I think we need a name for the thing that's not that - the thing that's current right now? "main" seems weird for a menu. Maybe Versions with the top option pointing at the normal build out of main being "latest"? and then a second option linking to the v0.8.0 one?

Another nuance - we want a banner on all these pages like Kubernetes has on old versions of docs, saying they're an old version and not being updated, like on https://v1-20.docs.kubernetes.io/docs/contribute/ - can we do that?

And finally, I like how the k8s docs have the (old) version in the url - can we do that on the openservicemesh.io domain? or must we use the netlify one (which is okay, but not as simple for users to understand).

**Comment by flynnduism** [comment]
## Version Dropdown

Perfect, I like _latest_ for this too. I've added that to the archival 0.8 branch, and issued a PR #45 to add to `main`.

## Banner

Added to the 0.8 archival branch. [Preview it here](https://release-v0-8.docs.openservicemesh.io/).

## Subdomain Structure

I've configured a subdomain for the archival branch deploy. Netlify auto formats this based off of the branch name:
https://release-v0-8.docs.openservicemesh.io/

It's a little long - we could shorten it (remove the `release-` part) by renaming the branch, though doing so would mean no longer mirroring the naming convention on the main repo. What do you think?

**Comment by bridgetkromhout** [comment]
> It's a little long - we could shorten it (remove the release- part) by renaming the branch, though doing so would mean no longer mirroring the naming convention on the main repo. What do you think?

I think it's okay for now - we can discuss it with the team and see if they have a preference. Thanks.

**Comment by bridgetkromhout** [comment]
@flynnduism can we use a pattern like https://istio.io/v1.9/docs/ or https://linkerd.io/2.9/overview/ - maybe https://docs.openservicemesh.io/v0.8? or https://v0-8.docs.openservicemesh.io/ if necessary. Also let's change `You are viewing archival docs for the 0.8.0 release. Latest docs are here.` to `You are viewing archival docs for the v0.8 release. Latest docs are here.`

**Comment by bridgetkromhout** [comment]
> 2. Use netlify.toml Redirects

This sounds like the best option to me - asking the dev leads their opinions as well.

**Comment by bridgetkromhout** [comment]
@draychev @ritazh Info that would be helpful:
- what you'd like the URL to look like (for example, you could have https://docs.openservicemesh.io/v0.8? or https://v0-8.docs.openservicemesh.io/) 
- what you'd like to populate this archived version of the v0.8 docs with - we started with what was in https://github.com/openservicemesh/osm/commits/release-v0.8/docs 5 days ago, which we incorrectly listed as 0.8.0 - it's actually 0.8.x. I think what's there now is fairly up to date - perhaps we need to bring in a PR from time to time if there are updates?

**Comment by shashankram** [comment]
Few things I think we should sort out regarding versioned documentation:
1. Should `latest` be built from `main` or the latest released version? Currently, OSM uses the `latest` image tag to refer to the latest released version. We do not have a specific tag to refer to the HEAD of `main`, but rather a Git commit SHA can be specified to use an image corresponding to that commit.
2. If we decide to render the documentation from `main` (which I think we should so that people have the opportunity to test the documentation and follow it to test features prior to cutting a release from `main`), we should ensure the documentation works when used against binaries built from `main`. This isn't the case right now because a lot of documentation related to install uses the `osm install` command without specifying image tags which default to the last released version. Because of this, a user following documentation from `main` will end up using a binary from the last released version, which is not guaranteed to be compatible with the documentation in `main`. (Related issue: https://github.com/openservicemesh/osm/issues/3371)

**Comment by bridgetkromhout** [comment]
> Should latest be built from main or the latest released version?

It seems like the usual choice for docs is latest released version. I know 0.8.x latest now, but I also think 0.9.x is going to be here very soon, right?

So I think we want to use "latest" on the website to refer to "latest released", not "main" - and any website changes that apply to an unreleased version should either be in a different branch or non-released until the software they apply to is available.

**Comment by shashankram** [comment]
> > Should latest be built from main or the latest released version?
> 
> It seems like the usual choice for docs is latest released version. I know 0.8.x latest now, but I also think 0.9.x is going to be here very soon, right?
> 
> So I think we want to use "latest" on the website to refer to "latest released", not "main" - and any website changes that apply to an unreleased version should either be in a different branch or non-released until the software they apply to is available.

My only concern as a user with making `latest` a moving target based on released versions is that the user could be unaware latest has changed to point to a different release without their knowledge. This can be made visible via a banner to draw attention.

**Comment by bridgetkromhout** [comment]
The banner has been in place for some time and this appears to be working.
