### ISSUE TITLE
Remove $ symbol from code blocks

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm-docs#375]
Some code blocks have the `$` in front of the command such that when you copy the block it'll copy the `$` as well so then the command doesn't run
![image](https://user-images.githubusercontent.com/69616256/170143268-14532c2e-f69c-40c4-8a3c-f70c906dcde7.png)

**Comment by shalier** [comment]
This could be fixed with https://github.com/openservicemesh/osm-docs/issues/374, it looks like the `$` is used to separate the command from the example output. But not entirely sure that #374 covers every instance of a code block having a `$`

**Comment by Santosh1176** [comment]
Hey, Can I take this up?

**Comment by Santosh1176** [comment]
Thanks, @shalier. Do you want me to remove all instances of `$` and `#` from the docs or is there any specific set of docs where this needs to be done?

**Comment by shalier** [comment]
@Santosh1176 Removing all instances of `$` should be enough since that actively affects the copied code. 
`#` shouldn't affect the copied code so we're good to leave it.
I didn't have a specific set of docs in mind, but I think anywhere that we have copyable code should be looked at.

Thanks for working on this!
