### ISSUE TITLE
Add documentation/guidance on how to collect Envoy access logs

### ISSUE THREAD

**Issue by phillipgibson** [openservicemesh/osm-docs#385]
There is a use case to collect Envoy access logs to systems such as a SEIM for analytics and auditing. We should provide some baseline guidance on how this can be achieved using OSM. 

Ref https://github.com/openservicemesh/osm/issues/4797

**Comment by allenlsy** [comment]
I doubt if it's necessary to create documentation for this specific task. Once Envoy access log is enabled, the remaining task is actually collecting log from a Kubernetes container, which has little to do with OSM operation itself. Please comment.

**Comment by phillipgibson** [comment]
We're getting signal that this may not be as clear for customers on how to enable this completely.
