### ISSUE TITLE
Create demo for rotating the OSM root certificate using MRCs

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm-docs#434]
Create a demo that walks through the process of creating a new MRC resource, initiating rotation, and monitoring rotation.

In v1.3, OSM root certificate rotation is experimental and is not supported. The demo demonstrates the happy path rotation scenario. The goal of the demo is to provide users with enough instruction to be able to try root certificate rotation and provide feedback for OSM root certificate rotation in v1.4. 

The demo should cover the following scenarios:
- Rotating to use a different certificate provider (i.e. tresor -> cert-manager)
- Rotating to use a new ca from the same provider (i.e. cert-manager -> cert-manager with a different issuer) 
- Rotating to use a different trust domain

**Comment by jsturtevant** [comment]
This PR starts the demo: https://github.com/openservicemesh/osm-docs/pull/448
