### ISSUE TITLE
Add info on how to install OSM cli

### ISSUE THREAD

**Issue by steeling** [openservicemesh/osm-docs#437]
Our getting started docs say how to install OSM with the OSM cli, but we don't mention how to install the CLI itself.

Better yet if we add the cli to major package managers like apt, homebrew, chocolatey

**Comment by jsturtevant** [comment]
Which docs?  The getting start here has that info https://release-v1-2.docs.openservicemesh.io/docs/getting_started/setup_osm/#download-and-install-the-osm-command-line-tool

Having it work with common package managers would be good addition 👍
