### ISSUE TITLE
Broken links in Getting Started Section

### ISSUE THREAD

**Issue by lam-man** [openservicemesh/osm-docs#438]
There are several links broken in Getting Started Section in the docs. The sub-section with broken links is [Configure Traffic Split between Two Services](https://release-v1-2.docs.openservicemesh.io/docs/getting_started/traffic_split/). The broken links are: 

- traffic Splitting how to guide
- installation guide

I am wondering that do we follow any docs convention on links? I saw different methods on adding links in the docs.

**Comment by lam-man** [comment]
I will try to fix the broken links. However, I didn't find a way to take the issue. Not sure someone can assign it to me. Thanks!

**Comment by keithmattix** [comment]
Assigned it to you! Thanks for your conributions!

**Comment by jsturtevant** [comment]
Thanks for the updates!
