### ISSUE TITLE
update the menu design

### ISSUE THREAD

**Issue by flynnduism** [openservicemesh/osm-docs#44]
Relevent discussion [here](https://github.com/openservicemesh/osm-docs/pull/42#issuecomment-841530678).

The current three column layout is a lot of squishyness, it's worth looking at a simpler layout where we drop the right-hand-side summary menu (part of the Docsy default) and give the menu and contents more breathing room.

**Comment by bridgetkromhout** [comment]
Good notion. Also, and this is a small point, when I click into a menu item, it seems like the left sidebar goes back up to the top or some such? I lose my place of where I was. Maybe that will be addressed or maybe it's out of scope, but figured I should mention. Thanks.

**Comment by flynnduism** [comment]
@bridgetkromhout that irks me too. Docsy auto renders the menu to focus on the current tree/section as you move around, I don't really like that UX as that behavior is more like a breadcrumb than what should be a static menu.

I will experiment with reconfiguring this ([their docs](https://www.docsy.dev/docs/adding-content/navigation/#section-menu) show a way to freeze the menu via a `ul_show` param).

**Comment by bridgetkromhout** [comment]
> I will experiment with reconfiguring this (their docs show a way to freeze the menu via a ul_show param).

Awesome. I think that would be the one remaining menu design change to handle for this issue.

**Comment by flynnduism** [comment]
I forgot to detail that I included this change in #46 already, so it's in place. The menu tree will no longer change from subsection to subsection.
