### ISSUE TITLE
Website`s release tab issue

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm-docs#5]
https://docs.openservicemesh.io/ release tab not redirecting to correct pages of OSM releases.

**Comment by bridgetkromhout** [comment]
Thanks for reporting this issue, @mudit-01. We're currently not using the release tab, so I'll close this at this time.

**Comment by bridgetkromhout** [comment]
To update this, we did start using the release tab and it now brings you to the past releases. Thanks!
