### ISSUE TITLE
some words are discolored

### ISSUE THREAD

**Issue by SanyaKochhar** [openservicemesh/osm-docs#54]
**Bug description**: For example, "enable" shows as blue in PR https://github.com/openservicemesh/osm/pull/2941 and renders as red on the docs site: https://deploy-preview-2941--osm-docs.netlify.app/docs/tasks_usage/namespace_monitoring/#enable-metrics-for-a-namespace

Could be due to the theme being used per @flynnduism's comment: https://github.com/openservicemesh/osm/pull/2941#discussion_r597816432

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Words are the same color

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by zr-msft** [comment]
@SanyaKochhar are you still seeing the discoloration and theme issue? if not can you please close the issue?

**Comment by shashankram** [comment]
@SanyaKochhar could you clarify if this issue is persistent?

**Comment by zr-msft** [comment]
@SanyaKochhar if the type of the code fence is removed, then the entire block remains the same color. For example

````
```
osm namespace add <namespace>
```
````
yields:

<img width="835" alt="Screen Shot 2022-09-14 at 3 20 08 PM" src="https://user-images.githubusercontent.com/43684271/190255188-e1151bb8-06f4-402c-ad56-6c9f8de8a147.png">

Would that be preferable to the theme handling syntax highlighting? I don't feel like the `osm` command examples really need any highlighting.
