### ISSUE TITLE
duplicate docs links in website for doc

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm-docs#6]
https://docs.openservicemesh.io/ has 2 links for same (https://docs.openservicemesh.io/) location do we need 2 links?
![image](https://user-images.githubusercontent.com/53465654/113994924-65b5b400-9873-11eb-9854-e974a7de6e02.png)

**Comment by bridgetkromhout** [comment]
@flynnduism Do you think the link in the upper left (the "Open Service Mesh" and image) should go to the same place as "Home", to https://openservicemesh.io?

**Comment by flynnduism** [comment]
Yes home/OSM root makes more sense, rather than to the Docs home
