### ISSUE TITLE
Manual Demo Guide Step Fails

### ISSUE THREAD

**Issue by davedoering** [openservicemesh/osm-docs#60]
I have successfully followed the steps for the manual demo till below the link: 

[https://github.com/openservicemesh/osm/blob/136d902c61b6c0fc2d4eb98215fe3aff0d0e73f7/docs/content/docs/install/manual_demo/_index.md#create-Pods-Services-ServiceAccounts]

where the Kubectl command to create the service accounts fails with this error message:

**<< was unexpected at this time.** 

Is there a missing step at this point in the doc or is there an incorrect syntax in the command?

**Comment by bridgetkromhout** [comment]
Hi Dave, the manual demo in https://github.com/openservicemesh/osm/blob/136d902c61b6c0fc2d4eb98215fe3aff0d0e73f7/docs/content/docs/install/manual_demo/_index.md#create-Pods-Services-ServiceAccounts is old - let's make sure we are using the one in https://docs.openservicemesh.io/docs/install/manual_demo/

Can you please paste in the exact command and the error that gets displayed, into this issue? Thanks!

**Comment by bridgetkromhout** [comment]
My guess is the problem happens at https://docs.openservicemesh.io/docs/install/manual_demo/#create-pods-services-serviceaccounts and it might be related to running on Windows - can you clarify the environment you're testing on?

`kubectl apply -f - <<EOF` may or may not work if you're not on a Linux machine - perhaps there is a Windows equiv?

**Comment by bridgetkromhout** [comment]
@davedoering can you check to see if this problem occurs if you use [wsl2](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? We should determine if this is a "Windows cli versus Linux shell" issue.

**Comment by davedoering** [comment]
@bridgetkromhout Phill and I ran through the Docker and K8s install again with no errors on that part. To troubleshoot I then ran in Powershell on Windows 10 Enterprise 21H1 Build 19043.985:
- wsl -l -v and it reports WSL version 2 for Docker, Ubuntu. 
-  osm version and it reports: 
Version: v0.8.4; Commit: 3d923b3f2d72006f6cdaad056938c492c364196d; Date: 2021-05-18-19:14
- kubectl create namespace bookstore and it reports "namespace/bookstore created"
-  osm namespace add bookstore and it reports "Namespace [bookstore] successfully added to mesh [osm]"

However, when I enter the next Demo commands: 
kubectl apply -f - <<EOF 
>> apiVersion: v1
>> kind: ServiceAccount
>> metadata:
>>   name: bookstore
>>   namespace: bookstore

it reports numerous errors (full list in the attached screenshot):
- Missing file specification after redirection operator. At line:1 char:20 
- The '<' operator is reserved for future use. At line:1 char:21
- Missing expression after unary operator '-'. At line:4 char:1 + apiVersion: v1
- Unexpected token 'apiVersion:' in expression or statement. At line:18 char:4
- Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingFileSpecification

![OSM Kubectl Error](https://user-images.githubusercontent.com/54189540/118890322-52a2f480-b8b3-11eb-8ea4-286e480efd30.png)

**Comment by bridgetkromhout** [comment]
Ah, yes, these aren't command lines you can use (verbatim) with powershell; that is linux shell redirection. You can read more on https://stackoverflow.com/questions/60398794/powershell-error-missing-file-specification-after-redirection-operator - basically either we need to write a powershell-compatible option, or we need to tell people to run these in bash. Does it work for you if you use bash?

**Comment by bridgetkromhout** [comment]
Related: https://github.com/openservicemesh/osm-docs/issues/66

**Comment by davedoering** [comment]
@phillipgibson I note that the Demo step with the command:

 cp .env.example .env
./scripts/port-forward-all.sh

Fails in Bash with the error "cp: cannot stat '.env.example': No such file or directory"

**Comment by phillipgibson** [comment]
@davedoering I believe you may not have the OSM repo cloned to your computer. Let's make sure you have a local copy of the repo using the git clone https://github.com/openservicemesh/osm.git command. in your WSL.

**Comment by bridgetkromhout** [comment]
If you look at https://docs.openservicemesh.io/docs/install/manual_demo/#view-the-application-uis you will see this language: 
> In a new terminal session, run the following commands to enable port forwarding into the Kubernetes cluster from the root of the project directory.

This means you need to be in the root of the project directory to copy https://github.com/openservicemesh/osm/blob/main/.env.example.

**Comment by davedoering** [comment]
Opened new issue to install missing resources as part of the OSM install.

**Comment by bridgetkromhout** [comment]
New issue mentioned above (https://github.com/openservicemesh/osm-docs/issues/69) was closed by @shashankram as invalid. Let's add any clarification needed to the manual demo instructions.

**Comment by davedoering** [comment]
Resolved this issue:
1. OSM binary needs to be installed into WLS even though the doc has instructions for installing a WIndows version.
2. Run subsequent demo install steps using Bash and not Powershell.
3. Corrected doc to reflect these requirements.
