### ISSUE TITLE
Some powershell commands in the "How to Run the OSM Manual Demo" dont work

### ISSUE THREAD

**Issue by apoutney** [openservicemesh/osm-docs#66]
TBH: I'm not sure if its the documentation that is wrong or if its something in my environment or if there is an issue with the commands.

I have been following the "How to Run the OSM Manual Demo" and have encountered some issues 

First, in the section "Create the Bookstore Application Namespaces" the following script is supplied

`
for i in bookstore bookbuyer bookthief bookwarehouse; do kubectl create ns $i; done
`

However this results in the following error: 

> Missing opening '(' after keyword 'for'.

I managed to get around this by creating the namespaces individually.  

But then in the "Verify the Traffic Policy Mode" the following command is given:

`
kubectl get configmap -n osm-system osm-config -o json | jq -r '.data["permissive_traffic_policy_mode"]'
`

This produces the following error: 

> jq: error: permissive_traffic_policy_mode/0 is not defined at <top-level>, line 1:
> .data[permissive_traffic_policy_mode]
> jq: 1 compile error

I again managed to get around this, by using the kubectl describe command on the config map to check the permissive_traffic_policy_mode value.

Then, in the section "Permissive Traffic Policy Mode" the following command is given to update the config map:

`
kubectl patch ConfigMap osm-config -n osm-system -p '{"data":{"permissive_traffic_policy_mode":"true"}}' --type=merge
`

But again this doesnt work and responds with the following error: 

> Error from server: Invalid JSON Patch

Is it the documentation that is wrong? Or have I missed something?

**Comment by shashankram** [comment]
https://github.com/openservicemesh/osm-docs/issues/66#issuecomment-828755976
