### ISSUE TITLE
clarify banner regarding v0.8 docs

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm-docs#67]
Release v0.8.4 of OSM was released on 5/18/2021. The docs for release-v0.8 should not be marked as archived. We should only mark a version of documentation as archived when we are no longer supporting it.

The banner reads as follows, but a user  using `release-v0.8.x` of OSM should not use the `latest` docs pointing to the `main` branch because `main` docs might not be compatible with the code in `release-v0.8.x`.

![image](https://user-images.githubusercontent.com/21697719/119042011-2b5c2e00-b96c-11eb-9299-0d6030afd588.png)

**Comment by bridgetkromhout** [comment]
Let's reword the banner - we definitely need a banner because that's what all such projects use, but we'll want to ensure the wording isn't confusing.

Perhaps: "You are viewing docs for the v0.8 release. View main branch docs for the latest changes."

**Comment by bridgetkromhout** [comment]
for reference re: branch naming: https://github.com/openservicemesh/osm-docs/issues/36

**Comment by flynnduism** [comment]
I've reworded the `release-v0.8` site accordingly. [View here](https://release-v0-8.docs.openservicemesh.io/).

> You are viewing docs for the v0.8 release. View main branch docs for the latest changes.

<img width="1613" alt="Screen Shot 2021-05-26 at 9 44 43 AM" src="https://user-images.githubusercontent.com/686194/119699813-64cae880-be07-11eb-9f17-b64014c4bc21.png">
