### ISSUE TITLE
Manual Install Missing Service Deployments

### ISSUE THREAD

**Issue by davedoering** [openservicemesh/osm-docs#69]
Verified with @phillipgibson that the Manual Install is missing service deployments for both the bookbuyer and bookthief applications. https://docs.openservicemesh.io/docs/install/manual_demo/

**Comment by bridgetkromhout** [comment]
Hi @davedoering can you follow the steps at https://github.com/openservicemesh/osm-docs/blob/main/content/docs/install/manual_demo.md#checkpoint-what-got-installed and verify what did and did not get installed? Thanks.

**Comment by phillipgibson** [comment]
I've checked. The services for bookbuyer and bookthief are not in any of the yanks. It needs to be updated.

**Comment by shashankram** [comment]
> I've checked. The services for bookbuyer and bookthief are not in any of the yamls. It needs to be updated.

That's because OSM no longer required client apps (bookbuyer and bookthief) in the demo to be k8s services. As a result, limitations in previous releases <= v0.7 have been removed and the docs no longer need to create services for bookbuyer and bookthief apps.

**Comment by shashankram** [comment]
> > I've checked. The services for bookbuyer and bookthief are not in any of the yamls. It needs to be updated.
> 
> That's because OSM no longer requires client apps (bookbuyer and bookthief) in the demo to be k8s services. As a result, limitations in previous releases <= v0.7 have been removed and the docs no longer need to create services for bookbuyer and bookthief apps.

Here's the reference to the issue in the OSM repo addressing this limitation: https://github.com/openservicemesh/osm/issues/2064

I am closing this issue since the bookbuyer and bookthief apps no longer need to be associated with a service.
