### ISSUE TITLE
doc: Ingress

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-docs#76]
This GitHub issue is for fleshing out the OSM documentation around XYZ:

 - [x] Document Ingress -- save the doc in ./docs/wip/ingress.md (unless this already exists) (exact location is TBD - `wip` short term)
   - [x] What is ingress?
   - [x] Why do I need it on my cluster?
   - [x] What types of ingress are supported by v0.8?
   - [x] What are sample Ingress resources that would work with v0.8?
   - [x] How does it work?
   - [ ] What's a sample Envoy configuration for a pod affected by Ingress?
   - [ ] What pods are affected by Ingress? (List Ingress, Service, Endpoints)
   - [ ] Are there different versions of the Ingress resource?
   - [x] Which version of the k8s Ingress resource is supported by OSM Controller v0.8? 
   - [ ] Point to docs w/ Nginx openservicemesh/osm#2827 and AGIC openservicemesh/osm-docs#75
 
 - [x] Create a small demo with sample apps and SMI showing how this feature works

 - [ ] List Common Issues
    - [ ] See GitHub Issues for Nginx openservicemesh/osm#2827 and AGIC openservicemesh/osm-docs#75  for ideas on common issues and troubleshooting

 - [x] Create Troubleshooting Guide
   - [x] List Ingress resources
   - [x] List Services referenced by an Ingress resource
   - [ ] List the Endpoints for a given Service to discover the Envoys affected
   - [ ] What are the Pods / Envoys referenced by a given Ingress resource
   - [ ] Do the Envoys referenced by an Ingress resource have config indicating that they have been properly programmed?
   - [ ] What is the Envoy config we would expect to see on Envoys referenced by an Ingress resource?

 - [ ] Automate Troubleshooting Guide in `pkg/troubleshooter` (create appropriate functions) - alternatively create a GitHub Issue with the stub of the function that could be eventually created within `pkg/troubleshooter` package to automatically troubleshoot this feature.

**Comment by zr-msft** [comment]
@shashankram @draychev It seems like there was a WIP doc, but that has been removed. Is this issue still relevant or should it be closed?

**Comment by shashankram** [comment]
> @shashankram @draychev It seems like there was a WIP doc, but that has been removed. Is this issue still relevant or should it be closed?

Ingress is documented here: https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/ingress/

Feel free to close this and #77 if you think the documentation is good enough.

**Comment by zr-msft** [comment]
thank you @shashankram, closing this issue
