### ISSUE TITLE
Use relative links in docs where possible instead of versioned absolute URL paths

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm-docs#8]
**Please describe what should be documented
Update links to be relative where possible in docs/content so that we don't have issues in the docs site where the link points to a document for a different version

**Please suggest where in the repo the document should be located
This applies to everything under docs/content

**Comment by bridgetkromhout** [comment]
We have a number of links to `release-v0.8` content that should be clarified or change.

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/openservicemesh/osm-docs/issues/22.
