### ISSUE TITLE
docs: Permissive Traffic Mode

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-docs#81]
This GitHub issue is for fleshing out the OSM documentation around Permissive Traffic Mode. 

 - [x] Document Permissive Traffic Mode -- save the doc in ./docs/wip/permissive_traffic_mode.md (exact location is TBD - `wip` short term)
   - [ ] Why do we need Permissive Traffic Mode? What value does it add?
   - [ ] What is the alternative? (What's the anti-permissive traffic mode?)
   - [ ] How do you switch to Permissive Traffic Mode? How do you switch to SMI mode? Are there more than one way to switch?
   - [ ] How does it work?
   - [ ] What is a sample Envoy config with Permissive Traffic Mode on and off?

 - [x] Create a small demo with sample apps and SMI showing how this feature works
   - [ ] Is there a common app (2 apps) where we can show a minimal configuration w/ permissive traffic mode works and without it does not work - without SMI policies?
 - [ ] List Common Issues
   - [ ] Are pods not wrapped in a k8s service going to have access to a destination service they connect to? 
 - [x] Create Troubleshooting Guide
   - [ ] Is the right config map changed?
   - [ ] Is the key in the config map connect?
   - [ ] Is the value in the config map correct?
   - [ ] What if the Validation Webhook fails? What's the error one could see? How do we work around it?
   - [ ] Has the OSM Controller picked up the change? (Is this visible in logs? Is this visible in events? Is this visible via some HTTP debug API? Should we create a task for this state to be exposed via the debug APIs?)

 - [ ] Automate Troubleshooting Guide in `pkg/troubleshooter` (create appropriate functions) - alternatively create another GitHub issue with a sample function signature - what could it check to see if things are working ok?

**Comment by zr-msft** [comment]
@draychev @phillipgibson this issue needs a demo to be completed

**Comment by shashankram** [comment]
> @draychev @phillipgibson this issue needs a demo to be completed

@zr-msft There is already a demo for this: https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/permissive_traffic_policy_mode/#sample-demo

**Comment by zr-msft** [comment]
moving this out of the documentation project but leaving open for @draychev

**Comment by shashankram** [comment]
Documented at https://docs.openservicemesh.io/docs/guides/traffic_management/permissive_mode/ and https://docs.openservicemesh.io/docs/guides/troubleshooting/traffic_management/permissive_traffic_policy_mode/
