### ISSUE TITLE
doc: Move and reorganize all newly written docs for v0.8

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-docs#83]
This GitHub issue is for the reorganization of all newly written docs for v0.8, which we wrote as part of https://github.com/openservicemesh/osm/issues/2854

**Comment by bridgetkromhout** [comment]
All docs that we plan to move to the osm-docs repo have been moved, and now all open issues we plan to move to this repo have also been moved. As we have https://github.com/openservicemesh/osm-docs/issues/84 which goes into more detail regarding reorganization, I'll close this issue now.
