### ISSUE TITLE
[docs] organize the docs

### ISSUE THREAD

**Issue by flynnduism** [openservicemesh/osm-docs#84]
The work in openservicemesh/osm#1840 creates a site to hold the docs, but it does not reformat the existing docs into it.

That work is best separated and added in after openservicemesh/osm#1840 - (i) to avoid a bunch of conflicts with other in-flight pull requests and (ii) ideally carried out by the OSM team to ensure editorial accuracy.

I'm creating this issue to recommend some edits:

- [x] create a proper welcome/landing page (currently a [placeholder](https://github.com/openservicemesh/osm/blob/main/docs/content/_index.md))
- [x] add front matter (see readme [notes](https://github.com/openservicemesh/osm/tree/main/docs#editing-content))
- [x] migrate the existing files into from `docs/*` to `docs/content/*` [here](https://github.com/openservicemesh/osm/tree/main/docs/content) 
- [x] review the current subsections (design, patterns) and organize the files for user flow (intro / getting started / install / examples / etc)  
- [x] review and fix links

**Comment by bridgetkromhout** [comment]
From @phillipgibson -

* Getting Started
  * Remove “Full feature demo” prefixes
  * Move manual demo up
  * Remove All OSM demos page – they will be included in the Tasks section
  * Remove OpenShift link. This should be part of the Installation target links
* Installation
  * Should have installation target links (OpenShift, AWS, GKE, Azure)
* Design & Concepts – Change to “Concepts and Features”
  * OSM Components & Interactions should be removed
  * In High-level software architecture the “source” link needs to be removed
  * Remove all design to a Design section
  * Change “Components & Descriptions” to just “Components”
  * Pod Lifecycle should be removed
  * Signaling should be removed
  * Interfaces should be removed
  * Design Appendix should be removed
* Tasks and Usage – Change section to just “Tasks”
  * Remove “Application Container Startup”
  * Change Certificates to “Configuring Certificates”
  * Change Namespace Monitoring to “Onboarding Namespaces”
  * Change Observability to “Configuring Observability”
  * Change Sidecar Injection to “Configuring Sidecar Injection”
  * Change Traffic Management to “Configuring Traffic Management”
* API Reference – Should be moved to last in the list
* Application Requirements – Section should be removed and info should be placed in a prerequisite section
* HA Design considerations – should be moved to new “Concepts and Features” section
* Health Probes: Applications – should be moved to “Tasks” section and named “Configure Health Probes”
* Health Probes: OSM Control Plane – should be moved to “Design and Concepts” section named OSM Control Plane Health Probes
* Integrations – Section should be removed. Links should be listed under “Tasks” section both with Integrate title link.
* OSM MeshConfig – Section should be removed and listed under “Concepts and Features”
* Scale and Limits – Section should be removed. If there are ceiling metrics a user needs to know that should be a part of the prerequisite section
* Troubleshooting – Section should be removed. Each link can go under the accompanying section from previous

**Comment by bridgetkromhout** [comment]
I have a few unfinished docs-move tasks - will sync with @phillipgibson for clarity on the ones I haven't yet checked off, to wit:
- Should have installation target links (OpenShift, AWS, GKE, Azure)
- Remove all design to a Design section
- Scale and Limits – If there are ceiling metrics a user needs to know that should be a part of the prerequisite section

To see the reorganization thus far, see https://deploy-preview-120--osm-docs.netlify.app/

**Comment by zr-msft** [comment]
@bridgetkromhout nice work on the PR! 

@phillipgibson @bridgetkromhout After looking at the updated docs organization, i left some minor feedback to swap the concepts/tasks position in the toc.

The tasks section is also still really long. Would you two be open to creating a "demos" or "examples" TOC item for better organization? Alternatively, can we replace "tasks" with several smaller groups, eg "configure observability", "configure traffic management", "configure services"? 

Also, I feel like "upgrade" should be part of install.

**Comment by phillipgibson** [comment]
Agreed @bridgetkromhout upgrade and uninstallation should be a part of the install group that expresses the installation lifecycle.

**Comment by zr-msft** [comment]
Closing out this task and will evaluate additional re-organization efforts in another task.
