### ISSUE TITLE
Docs and demo should make osm namespace more generic

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm-docs#87]
**Please describe what should be documented

Currently docs and demos assume osm control-plane is installed in the `osm-system` namespace. We should make this more generic.

**Please suggest where in the repo the document should be located

**Comment by shashankram** [comment]
I have updated the demo docs to not hardcode the install namespace: https://docs.openservicemesh.io/docs/demos/
osm-system is still being used as a default in some docs for convenience.
