### ISSUE TITLE
Document usage of SMI traffic splitting and dependency on apex service

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm-docs#89]
**Please describe what should be documented
SMI traffic split uses an apex service, with the apex service being a Kubernetes Service resource. The apex service needs to be configured correctly (have the right namespace, port, selectors etc.) to be able to split traffic to leaf services.

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/tree/main/docs/patterns

**Comment by jaellio** [comment]
This issue will be addressed in [https://github.com/openservicemesh/osm-docs/issues/88](https://github.com/openservicemesh/osm-docs/issues/88)
