### ISSUE TITLE
Docs contain links that are either broken in Github or the website

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm-docs#9]
**Please describe what should be documented
Various links in the repo are broken either in the website or on Github. We should standardize how we link to docs to ensure they work both in the repo and on the site.

Links should:

1. Maintain the tree when switching between docs in the Github site
2. Maintain the version when switching between docs on the website
~~3. Work for both the site and the Github repo~~

**Please suggest where in the repo the document should be located

**Comment by bridgetkromhout** [comment]
I have made a first pass through and fixed many links. It's probably worth another pass.

**Comment by bridgetkromhout** [comment]
I have fixed more broken links, and this is probably complete enough at this point to close this as a task.
