### ISSUE TITLE
doc: Create a new section in docs / front page listing all possible mini-demos

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm-docs#95]
Create a new section in front-page docs and list all possible demos we have created as part of this task
 - [ ] TrafficSplit
 - [ ] TCPRoute
 - [ ] gRPC
 - [ ] Ingress
   - [ ] Nginx
   - [ ] AGIC 
 - [ ] Egress

**Comment by bridgetkromhout** [comment]
@draychev do we still want "Demos" as a top level sections similar to Getting Started, Design & Concepts, etc? Or do we want demos sorted by area, like tasks_usage/traffic_management/demos? Or something else?

**Comment by zr-msft** [comment]
landing page updated
