### ISSUE TITLE
Demo Install step lacks a resource

### ISSUE THREAD

**Issue by davedoering** [openservicemesh/osm-docs#98]
The first command at https://docs.openservicemesh.io/docs/install/manual_demo/#view-the-application-uis is:

cp .env.example .env
./scripts/port-forward-all.sh

However, this produces an error message: "cp: cannot stat '.env.example': No such file or directory." The automated demo doc suggests the user needs to create the env file. However,  no such step is in the manual doc. 

Checked that the  ./scripts/port-forward-all.sh file does exist.

**Comment by bridgetkromhout** [comment]
I addressed this in https://github.com/openservicemesh/osm-docs/issues/60#issuecomment-846215075.

**Comment by davedoering** [comment]
@bridgetkromhout @phillipgibson  I went through the procedure mentioned in your #60 comment, and yes, the command ran without this error I saw earlier. The output is below (is this the expected output?):

v-ddoering@BCSR-DDOERING:~/github.com/osm$ cp .env.example .env
cripts/port-forward-all.sh
v-ddoering@BCSR-DDOERING:~/github.com/osm$ ./scripts/port-forward-all.sh
No resources found in osm-system namespace.
Forwarding from 127.0.0.1:8080 -> 14001
Forwarding from [::1]:8080 -> 14001
error: resource name may not be empty
No resources found in osm-system namespace.
No resources found in bookstore namespace.
No resources found in bookstore namespace.
Forwarding from 127.0.0.1:8084 -> 14001
Forwarding from [::1]:8084 -> 14001
error: resource name may not be empty
error: resource name may not be empty
error: resource name may not be empty
Forwarding from 127.0.0.1:9092 -> 9092
Forwarding from [::1]:9092 -> 9092
Forwarding from 127.0.0.1:8083 -> 14001
Forwarding from [::1]:8083 -> 14001

**Comment by phillipgibson** [comment]
I believe the shell command needs to be updated. It's referencing resources that are not available in the cluster to port forward.

**Comment by davedoering** [comment]
Who would I refer to to update the shell command?

**Comment by bridgetkromhout** [comment]
Closing in favor of https://github.com/openservicemesh/osm/issues/3521.
